### ISSUE TITLE
Unclear Hypothesis exception on minimal example

### ISSUE THREAD

**Issue by thilp** [Zac-HD/hypothesis-jsonschema#16]
Hi, thank you for your efforts in combining Hypothesis with JSON Schema!

My understanding from the readme is that hypothesis-jsonschema works like this:
```py
>>> from hypothesis_jsonschema import from_schema
>>> schema = {'properties': {'x': {'type': 'string'}}}
>>> from_schema(schema).example()  # would return something like {'x': 'hi'}
```
Turns out I get a `hypothesis.errors.InvalidArgument: Cannot use strategy data() within a call to find (presumably because it would be invalid after the call had ended)` instead (full stacktrace below).

Sometimes, with the exact same schema, I will not get an exception, but a boolean result instead. I suppose this is also an unexpected behavior given the above schema, which describes an object.

I'm not familiar with Hypothesis internals, so I really have no clue where to start investigating. Am I doing something stupid?

I'm using:
- Hypothesis v4.24.5
- hypothesis-jsonschema v0.9.3

<details>
<summary>Stacktrace</summary>

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../hypothesis/searchstrategy/strategies.py", line 309, in example
    phases=tuple(set(Phase) - {Phase.shrink}),
  File ".../hypothesis/core.py", line 1112, in find
    runner.run()
  File ".../hypothesis/internal/conjecture/engine.py", line 398, in run
    self._run()
  File ".../hypothesis/internal/conjecture/engine.py", line 766, in _run
    self.generate_new_examples()
  File ".../hypothesis/internal/conjecture/engine.py", line 700, in generate_new_examples
    self.test_function(last_data)
  File ".../hypothesis/internal/conjecture/engine.py", line 144, in test_function
    self.__stoppable_test_function(data)
  File ".../hypothesis/internal/conjecture/engine.py", line 127, in __stoppable_test_function
    self._test_function(data)
  File ".../hypothesis/core.py", line 1083, in template_condition
    result = data.draw(search)
  File ".../hypothesis/internal/conjecture/data.py", line 829, in draw
    return self.__draw(strategy, label=label)
  File ".../hypothesis/internal/conjecture/data.py", line 844, in __draw
    return strategy.do_draw(self)
  File ".../hypothesis/searchstrategy/strategies.py", line 497, in do_draw
    return data.draw(self.element_strategies[i], label=self.branch_labels[i])
  File ".../hypothesis/internal/conjecture/data.py", line 829, in draw
    return self.__draw(strategy, label=label)
  File ".../hypothesis/internal/conjecture/data.py", line 838, in __draw
    return strategy.do_draw(self)
  File ".../hypothesis/searchstrategy/lazy.py", line 156, in do_draw
    return data.draw(self.wrapped_strategy)
  File ".../hypothesis/internal/conjecture/data.py", line 829, in draw
    return self.__draw(strategy, label=label)
  File ".../hypothesis/internal/conjecture/data.py", line 838, in __draw
    return strategy.do_draw(self)
  File ".../hypothesis/_strategies.py", line 1856, in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
  File ".../hypothesis_jsonschema/_impl.py", line 594, in from_object_schema
    draw(st.data()).conjecture_data,
  File ".../hypothesis/internal/conjecture/data.py", line 820, in draw
    % (strategy,)
hypothesis.errors.InvalidArgument: Cannot use strategy data() within a call to find (presumably because it would be invalid after the call had ended).
```

</details>

**Comment by Zac-HD** [comment]
Oh, I see what's happening. The short version is that `from_schema` is only meant to be used to create test functions with Hypothesis' `@given(...)` decorator.

The long version is that for complicated internal reasons involving lazy evaluation, it sometines produces a simple example without raising an error. The example() method is only meant for interactive exploration though, so please just use given!

And finally, a boolean actually does match that schema! Unless you add the "type" key, any type is allowed and the "properties" key applies if and only if the value is of type object. Surprises like this are part of why I maintain hypothesis-jsonschema: we need all the help we can get.

**Comment by thilp** [comment]
Thank you for taking a look so soon, and for pointing out the reason for these booleans.

I was definitely planning to use `@given` but I played with `example()` because I was getting some error (don't remember which one, almost certainly my fault) so I wanted to manually check out what the strategy was returning. If I might, I would suggest documenting this detail about `example()` in the readme, to help new users that are experimenting before actually using (they would not think hypothesis-jsonschema doesn't work, and it would spare you issues like this one).

Now (with `@given`) I get the dreadful `hypothesis.errors.FailedHealthCheck` ("Health check found 50 filtered examples but only 0 good ones") so it looks like the niceties of hypothesis-jsonschema will still be out of my reach for some time, because my schema (for a Kubernetes CRD) is too big. :disappointed: 

Thanks for your help, and keep up the good work! To me, hypothesis and JSON Schema look like an obvious marriage, so I'm glad you actually did it! :+1:

**Comment by Zac-HD** [comment]
No problem! I'm actually planning to improve the example() method upstream instead 😉

You can also just disable that health check - the test will be less efficient but if there's no better alternative who cares? Admittedly 0/50 may not work even if it just keeps trying... 

If you can share the schema, I'd be happy to add it to the test suite or at least try to get it working! No promises on timing but making something useful is the whole point here 🙂

**Comment by thilp** [comment]
> You can also just disable that health check - the test will be less efficient but if there's no better alternative who cares? Admittedly 0/50 may not work even if it just keeps trying...

I've fallen back to `pytest.mark.parametrize`. I think that increasing Hypothesis' timeout would be overkill for my very basic use-case.

> If you can share the schema, I'd be happy to add it to the test suite or at least try to get it working! No promises on timing but making something useful is the whole point here

Sure, I've replaced business-specific names (I assume this changes nothing for the strategy) and pasted it in YAML below. I'm glad if it can enrich your tests, but don't worry too much about it: in my experience, hand-written Hypothesis strategies using `builds()` for relatively decent nested objects also often trigger the timeout, so I'm used to liberally replacing `text()` and `integers()` with `just()` or `sampled_from()` to reduce the search space. I'm not surprised that hypothesis-jsonschema struggles here, without the help of these manual (and highly domain-specific) optimizations.

<details>
<summary>My schema</summary>

```yaml
---
type: object
required:
  - apiVersion
  - kind
  - metadata
  - spec
properties:
  apiVersion:
    type: string
    enum: [example.com/v1]
  kind:
    type: string
    enum: [B]
  metadata:
    type: object
    required:
      - name
      - namespace
      - labels
      - ownerReferences
    properties:
      name:
        type: string
        minLength: 1
      namespace:
        type: string
        minLength: 1
      labels:
        type: object
        required: [application]
        properties:
          application:
            type: string
            minLength: 1
      ownerReferences:
        type: array
        items:
          type: object
          required:
            - apiVersion
            - kind
            - name
          properties:
            apiVersion:
              type: string
              enum: [example.com/v1]
            kind:
              type: string
              enum: [A]
            name:
              type: string
              minLength: 1
  spec:
    type: object
    required:
      - a
      - b
      - c
      - d
      - e
      - f
    properties:
      a:
        type: string
        minLength: 1
      b:
        type: string
        minLength: 1
      c: &duration-validation
        type: string
        pattern: '^\d+[hms]$'
      d: *duration-validation
      g: *duration-validation
      e:
        type: array
        items:
          type: object
          required: [x, y]
          properties:
            x:
              type: string
            y:
              type: string
      f:
        type: string
        minLength: 1
```

</details>

**Comment by Zac-HD** [comment]
Closed by the `.example()` upgrades in [Hypothesis 4.27](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-27-0), which were prompted by this issue.
