### ISSUE TITLE
How to specify alphabet for certain string field in jsonschema file?

### ISSUE THREAD

**Issue by ke-zhang-rd** [Zac-HD/hypothesis-jsonschema#20]
I have a field `"name"` with `"type": "string" `in jsonschema file. Is there any approach to specify `alphabet` when I do `hypothesis_jsonschema.from_schema` for `name` field. OR any other way to go around it to avoid `'\U000e7228\U000edb03\U000fa8b4\U000eadf5\U000687c6\U0005b0d4\U000b83fb'` and get something more human readable?

I have this question because `string` in jsonschema looks mapping to `text` in hypothesis. If `hypothesis.strategies.text` has such argument, It would be nice make string field from jsonchema has.

Thanks.
Ke

**Comment by Zac-HD** [comment]
As a design choice, `from_schema` will never be customisable - you can get anything that's allowed by the schema.

That said, you can use the "pattern" keyword in your schema to specify a regular expression that the string must match, such as "[A-Z][a-z]*". 

I hope that helps!

**Comment by ke-zhang-rd** [comment]
That helps. thanks.
