### ISSUE TITLE
Resolve all references before canonicalising

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/hypothesis-jsonschema#28]
Currently, we don't handle schemas with references at all - in our test suite, schema with `$ref` keys just get skipped.  Ideally the first step of canonicalisation would be to replace each reference with the referred-to schema, and raise an explicit error if there are any recursive references.

**Comment by rebcabin** [comment]
I was just about to post an MVE on this issue; glad to see you're already aware of it :)

**Comment by Zac-HD** [comment]
Prototype: https://github.com/Zac-HD/hypothesis-jsonschema/compare/refs

As far as I can tell it basically all works as expected, but getting the tests to skip schemas with recursive references (without skipping anything else) is surprisingly tricky.

Testing against the larger real-world schemas also blows the test suite out from <1 to >10 minutes, which is not fun.  Unclear whether this is because the code is slow or just doing a lot more work, but I'm leaning towards "both, and that's a perf bug".  We'll see when I get back to this.

**Comment by Zac-HD** [comment]
Closed by fd4f89787cf0d2896e6b2ba748041443e5a3a26e :tada:

**Comment by andylamp** [comment]
sorry to reopen this, however this fails for local resources as well e.g. - if I construct a `$ref` using `file://path/to/my/schema_ref.json`  - it still thinks it's a remote URI; can this be changed relatively easily...?

**Comment by Zac-HD** [comment]
Hi @andylamp - it's true that you're *probably* not going across the network (NFS!), but reading from a local disk is still IO.  I'll open an issue to support this somehow, though it will be off-by-default and might be a while before it's implemented 🙂

**Comment by andylamp** [comment]
@Zac-HD, if you can point me to some resources I'll probably to create a patch for this myself 😉

**Comment by Zac-HD** [comment]
I'm afraid I don't have any suggestions beyond "look at how the jsonschema library does it", but I'll be happy to review and merge a patch! (don't feel that you have to be done before opening a PR either, I'm happy to see WIPs)
