### ISSUE TITLE
$ref fails when in items of an array

### ISSUE THREAD

**Issue by acstarr** [Zac-HD/hypothesis-jsonschema#32]
`$ref` fails when in items of an array.  The `jsonschema` code seems to be trying to find the `definitions` key in the object describing the array.  Here is an example schema that fails:

```json
{
    "type": "object",
    "definition": {"type": "string"},
    "properties": {
        "something": {
            "type": "array",
            "items": {"$ref": "#/definition"}
        }
    }
}
```

Here is the trace:

```python-traceback
Traceback (most recent call last):
  File "python3.7/site-packages/jsonschema/validators.py", line 811, in resolve_fragment
    document = document[part]
KeyError: 'definitions'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test_REDACTED.py", line 13, in test_doesnt_crash
    def test_doesnt_crash(self, features):
  File "python3.7/site-packages/hypothesis/core.py", line 1080, in wrapped_test
    raise the_error_hypothesis_found
  File "python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 458, in from_object_schema
    out[key] = draw(merged_as_strategies(pattern_schemas))
  File "python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 48, in merged_as_strategies
    return from_schema(schemas[0])
  File "python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 86, in from_schema
    schema = resolve_all_refs(schema)
  File "python3.7/site-packages/hypothesis_jsonschema/_canonicalise.py", line 511, in resolve_all_refs
    schema[key] = res_one(val)
  File "python3.7/site-packages/hypothesis_jsonschema/_canonicalise.py", line 495, in res_one
    with resolver.resolving(ref) as got:
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "python3.7/site-packages/jsonschema/validators.py", line 754, in resolving
    url, resolved = self.resolve(ref)
  File "python3.7/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "python3.7/site-packages/jsonschema/validators.py", line 781, in resolve_from_url
    return self.resolve_fragment(document, fragment)
  File "python3.7/site-packages/jsonschema/validators.py", line 815, in resolve_fragment
    "Unresolvable JSON pointer: %r" % fragment
jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/some_def'
```

**Comment by Zac-HD** [comment]
😕 weird... there's definitely a bug somewhere in there, but I'm not sure how to fix it.  

Thanks for an excellent report, though - that's always the first step!

**Comment by bollwyvl** [comment]
I am also running into this, and don't have a lot of control over my schema to avoid it: it's generating it from some source code, and unions, etc. just kinda end up looking this way.

With some additional instrumentation, I found one call to `from_schema` will actually generate more than one `RefResolver`: I sort of got this to pass by hacking the `resolver` argument into... [everything](https://gist.github.com/bollwyvl/77984691a619aa6cb61a495f28ec5d2e). But this hardly seems desirable, and fails other tests. It seems like the user-facing `from_schema` might need to initialize and own the resolver, and make that available for all subsequent resolutions. 

Some options might be:
- what that gist does
  - though probably make it a more extensible `context` dataclass/typeddict
- have a class with most of the internals hanging off of it, for that one bit of `resolver` state
  - seems counter to the current architecture
- [contextvars](https://docs.python.org/3/library/contextvars.html) (with a [backport](https://github.com/MagicStack/contextvars) (missing asyncio, but seems irrelevant to this case))
  - new (potential) dependency, but might be worth it... have seen this applied in other places to handle issues like this, but this, too, could be "too much"

Also, and sort of on-topic, in the tests, `xfail_on_reference_resolve_error` is perhaps swallowing up too many things... checking the `_cause` for various strings might avoid false positives.

**Comment by Zac-HD** [comment]
Thanks for investigating!  Dumping some random thoughts in the thread:

- We shouldn't need to do anything too complicated with passing around the resolver or contextvars - the idea of `resolve_all_refs` is that it recurses until it's resolved *all* the references.  Only after that's finished do we pass the schema off to be canonicalised and later converted to a strategy.

- Creating multiple resolvers is an accidental side-effect of the current design - `from_schema()` can recurse, and unconditionally calls `resolve_all_refs`.  If we only attempt to resolve schemas that actually contain a `$ref` keyword somewhere this should go away.  I wouldn't expect that to fix anything though, as the second and later calls shouldn't do anything (though there's clearly a bug somewhere, and maybe it's here).

- Improving tests is always nice!  If you're up for it I'd love a PR :wink:

**Comment by anentropic** [comment]
I realise "me too" comments are necessarily helpful, but maybe other examples can be useful...

I ran into this using https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json as the `from_schema`

getting error:
```
E               jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/Reference'

/lib/python3.7/site-packages/jsonschema/validators.py(781)resolve_from_url()
    779                 raise exceptions.RefResolutionError(exc)
    780
--> 781         return self.resolve_fragment(document, fragment)
    782
    783     def resolve_fragment(self, document, fragment):

ipdb> document
{'oneOf': [{'$ref': '#/definitions/Reference'}, {'$ref': '#/definitions/Response'}]}
```

The required `definitions` are all there https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json#L53

As noted in the other comments, it seems to be trying to resolve the JSON Pointer ref against a small local piece of the document?

**Comment by bollwyvl** [comment]
@anentropic alas, while #34 handles this issue's `$ref` case (and a few other, besides), it won't help with OpenAPI 3.0, which has recursive references a la #33... and as pointed out there, it is a fair amount more involved than what ended up being a fairly small fix for this class of issues.

**Comment by bollwyvl** [comment]
ah, the recursive schema in OpenAPI is... an embedding of some derivative of JSON Schema for itself. that'll do it!
