### ISSUE TITLE
Calculate number of allowed integers for a schema

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/hypothesis-jsonschema#38]
As part of our canonicalisation logic, it can be really useful to know how many unique values a schema permits.  That's sometimes hard to calculate, but we try to cover the simple cases with `upper_bound_instances()`:

https://github.com/Zac-HD/hypothesis-jsonschema/blob/20a0fb1a44c8bc031d9b99e19be1eceff08cce69/src/hypothesis_jsonschema/_canonicalise.py#L132-L143

If we have a list (`array`) schema where the list items need to be unique and there aren't enough to fill the minimum size, it's impossible to generate a matching list:

https://github.com/Zac-HD/hypothesis-jsonschema/blob/20a0fb1a44c8bc031d9b99e19be1eceff08cce69/src/hypothesis_jsonschema/_canonicalise.py#L308-L312

---------

So this issue is to add support for `type: integer` schemas to `upper_bound_instances`.  If [`get_integer_bounds()`](https://github.com/Zac-HD/hypothesis-jsonschema/blob/20a0fb1a44c8bc031d9b99e19be1eceff08cce69/src/hypothesis_jsonschema/_canonicalise.py#L192-L207) are not `None`, calculating the number of allowed integers isn't too hard - even accounting for `multipleOf`.

And then [this test won't need `xfail` anymore](https://github.com/Zac-HD/hypothesis-jsonschema/blob/20a0fb1a44c8bc031d9b99e19be1eceff08cce69/tests/test_canonicalise.py#L105-L112), because we'll be able to canonicalise it to the empty schema as expected :tada:

**Comment by marielledado** [comment]
I'd like to try solving this issue by adding support for `type: integer` to `upper_bound_instances`

**Comment by Zac-HD** [comment]
Sounds great!

Main advice: open a pull request early, and push each chunk of work as you complete it - that way I can offer advice early if you're going down a dead end :slightly_smiling_face:

**Comment by Zac-HD** [comment]
Closed by #42 :tada:
