### ISSUE TITLE
Translate few-allowed-`integers` schemas to use `enum`

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/hypothesis-jsonschema#39]
After #38 is done, we'll have a nice way to check how many values are allowed for `type: integers` schemas.

When only a few integers are allowed, representing this as an `enum` can be more efficient - it's easier to merge schemas because we just check enum elements, and Hypothesis has some smarter logic for `lists(sampled_from(...), unique=True, ...)` strategies.  To implement this:

https://github.com/Zac-HD/hypothesis-jsonschema/blob/20a0fb1a44c8bc031d9b99e19be1eceff08cce69/src/hypothesis_jsonschema/_canonicalise.py#L287-L288

```python
elif type_ == ["integer"] and upper_bound_instances(schema) <= 256:
    allowed_values = ... # TODO your logic here
    return {"enum": allowed_values}
```

**Comment by akash-suresh** [comment]
Hey @Zac-HD! Is there a guide to setting it up on local?

Running `tox` is successful. But, when I run the tests individually, it's not able to find reference to `gen_schemas`.

**Comment by Zac-HD** [comment]
Huh, what command are you using?

You can pass extra arguments through though, like `tox -e test -- --lf` - anything after the `--` is passed as an argument to pytest.

**Comment by akash-suresh** [comment]
I meant that, `from gen_schemas import gen_number, json_schemata, schema_strategy_params`, this import is not getting resolved.

**Comment by Zac-HD** [comment]
I don't know what you're doing - please post the command you typed and the full output so I can try to reproduce it.

**Comment by akash-suresh** [comment]
Hey @Zac-HD. I was able to figure it out. Apologies for raising a silly issue.

**Comment by akash-suresh** [comment]
<img width="920" alt="Screen Shot 2020-06-02 at 9 33 50 PM" src="https://user-images.githubusercontent.com/10497294/83542587-cd46f880-a518-11ea-891a-634cfc00cfdd.png">

I haven't made any changes yet. There is one test case, which is failing on my local. 
```
Falsifying example: test_merge_semantics(
    data=data(...),
    s1={'maxProperties': 2,
     'minProperties': 2,
     'properties': {'1': {'type': 'integer'}},
     'type': 'object'},
    s2={'additionalProperties': {'type': 'null'},
     'properties': {'0': {}},
     'required': [''],
     'type': 'object'},
)
{'additionalProperties': {'const': None}, 'maxProperties': 2, 'minProperties': 2, 'properties': {'0': {}, '1': {'type': 'integer'}}, 'required': [''], 'type': 'object'}
Draw 1 (combined): {'': None, '0': None}
Draw 2 (s1): {'1': 0, '': None}
Draw 3 (s2): {'': None}
Traceback (most recent call last):
  File "/Users/300006798/Documents/WorkSpace/OpenSource/hypothesis-jsonschema/tests/test_canonicalise.py", line 345, in test_merge_semantics
    _merge_semantics_helper(data, s1, s2, combined)
  File "/Users/300006798/Documents/WorkSpace/OpenSource/hypothesis-jsonschema/tests/test_canonicalise.py", line 334, in _merge_semantics_helper
    assert is_valid(i1, s2) == is_valid(i1, combined)
AssertionError: assert False == True
 +  where False = is_valid({'': None, '1': 0}, {'additionalProperties': {'type': 'null'}, 'properties': {'0': {}}, 'required': [''], 'type': 'object'})
 +  and   True = is_valid({'': None, '1': 0}, {'additionalProperties': {'const': None}, 'maxProperties': 2, 'minProperties': 2, 'properties': {'0': {}, '1': {'type': 'integer'}}, ...})

Falsifying example: test_merge_semantics(
    data=data(...),
    s1={'maxProperties': 2,
     'minProperties': 2,
     'properties': {'0': {'type': 'integer'}},
     'type': 'object'},
    s2={'additionalProperties': {'type': 'null'},
     'required': [''],
     'type': 'object'},
)
{'additionalProperties': {'const': None}, 'maxProperties': 2, 'minProperties': 2, 'properties': {'0': {'type': 'integer'}}, 'required': [''], 'type': 'object'}
Draw 1 (combined): {'': None, '0': 0}
Draw 2 (s1): {'0': 0, '': None}
Draw 3 (s2): {'': None}
Traceback (most recent call last):
  File "/Users/300006798/Documents/WorkSpace/OpenSource/hypothesis-jsonschema/tests/test_canonicalise.py", line 345, in test_merge_semantics
    _merge_semantics_helper(data, s1, s2, combined)
  File "/Users/300006798/Documents/WorkSpace/OpenSource/hypothesis-jsonschema/tests/test_canonicalise.py", line 333, in _merge_semantics_helper
    assert is_valid(ic, s2)
AssertionError: assert False
 +  where False = is_valid({'': None, '0': 0}, {'additionalProperties': {'type': 'null'}, 'required': [''], 'type': 'object'})
```

**Comment by Zac-HD** [comment]
That's a bug alright, and apparently my computer just didn't find it no matter how long I ran the tests for... so deleting your `.hypothesis` directory will make it unlikely to randomly come back :sweat_smile: 

I'll take a more serious look at the merging logic for objects, at the very least to fix this bug but maybe also to improve it a bit.

**Comment by akash-suresh** [comment]
Hey @Zac-HD! This is what I am trying to do.

```
elif type_ == ["integer"] and upper_bound_instances(schema) <= 256:
    allowed_values = list(range(lo, hi + 1))
    if isinstance(mul, int) and mul > 1:
        allowed_values = list(filter(lambda i: (i % mul == 0), allowed_values))
    return {"enum": allowed_values}

```

Is this the right way?

**Comment by Zac-HD** [comment]
Yep, that looks like the correct logic!

- You can be a more efficient than filtering by using [the `step` argument for `range`](https://docs.python.org/3/library/stdtypes.html#range), otherwise `multipleOf: 1_000_000` would take a long time and a lot of memory!
- We *will* need to filter if `mul` is a float, though - use the `validator = make_validator(schema).is_valid` idiom.  This is still reasonably efficient because in this case we know that we're only considering ~255 integers in total (whereas with an integer multiplier we are considering that many *valid integers*, and who knows how many invalid)
- We'll want to keep the same shrinking order, i.e. `{"enum": sorted(allowed_values, key=lambda n: (abs(n), n < 0)}` so that `-2, ... 3` -> `[0, 1, -1, 2, -2, 3]`.

**Comment by akash-suresh** [comment]
> Yep, that looks like the correct logic!
> 
> * You can be a more efficient than filtering by using [the `step` argument for `range`](https://docs.python.org/3/library/stdtypes.html#range), otherwise `multipleOf: 1_000_000` would take a long time and a lot of memory!

Something like this? 
```
mul = schema.get("multipleOf", 1)
allowed_values = list(range(lo, hi + 1, mul))
```
> * We _will_ need to filter if `mul` is a float, though - use the `validator = make_validator(schema).is_valid` idiom.  This is still reasonably efficient because in this case we know that we're only considering ~255 integers in total (whereas with an integer multiplier we are considering that many _valid integers_, and who knows how many invalid)

I did not understand this. Could you explain a bit more?

> * We'll want to keep the same shrinking order, i.e. `{"enum": sorted(allowed_values, key=lambda n: (abs(n), n < 0)}` so that `-2, ... 3` -> `[0, 1, -1, 2, -2, 3]`.

Done.
```
return {"enum": sorted(allowed_values, key = lambda n: (abs(n), n < 0))}
```

**Comment by Zac-HD** [comment]
Open a pull request and I'll add the floats case in a commit 🙂

**Comment by Zac-HD** [comment]
As discussed on #52, it turns out that this is actually a net *loss* for performance, so we're not going to add it after all :disappointed:
