### ISSUE TITLE
Possible mishandling in `allOf` keyword canonicalisation

### ISSUE THREAD

**Issue by Stranger6667** [Zac-HD/hypothesis-jsonschema#65]
Consider the following schema:

```python
SCHEMA = {
    "allOf": [
        {"$ref": "#/definitions/ref"},
        {"required": ["foo"]}
    ],
    "properties": {
        "foo": {},
    },
    "definitions": {
        "ref": {"maxProperties": 1}
    },
    "type": "object"
}
```

If we call `jsonschema.validate({}, SCHEMA)` then it will complain that `'foo' is a required property` which is expected. But, if we canonicalise the schema, then `$ref` keyword will be placed to the schema's root and will cancel the validation of other keywords as implemented in [jsonschema](https://github.com/Julian/jsonschema/blob/master/jsonschema/validators.py#L305). I can't find the exact place in the spec itself, but there are tests in the JSON Schema suite that ensure that other keywords are ignored.

So, with the canonicalised version of the schema an empty object passes validation:

```python
>>> CANONICALISED = canonicalish(SCHEMA)
>>> jsonschema.validate({}, CANONICALISED)
```

What would be the best way to solve it? Should we check if there are schemas with `$ref` keywords, then keep them inside `allOf` and move everything else to the previous level?

P.S. I found the issue via `Webpack bootstrap-loader configuration file` schema in the testing catalog

**Comment by Zac-HD** [comment]
Canonicalising should remove the `$ref` keyword for non-recursive references, but we will probably need to add special handling for recursive references.

**Comment by Stranger6667** [comment]
> Canonicalising should remove the $ref keyword for non-recursive references

Aha, I missed that :) I found it in my experiment branch, where I didn't inline references at all.

> but we will probably need to add special handling for recursive references.

Would it make sense if I submit a PR that will handle it? I.e. to be future-compatible with recursive references? Or is it better to add it as a part of that recursive references PR?

**Comment by Zac-HD** [comment]
I'd be happy either way, but I don't think we can really test it separately so let's keep them together.

**Comment by Zac-HD** [comment]
This is still present in the latest version of `hypothesis_jsonschema` - apparently 

https://github.com/Zac-HD/hypothesis-jsonschema/blob/927fbf8f26a1e6fd88ddcd953a6720fe369095a9/src/hypothesis_jsonschema/_canonicalise.py#L599-L610

is insufficient in this case.  Adding some tests or assertions that there are no `"$ref"` keywords left unless there are recursive references should help narrow this down...

**Comment by Zac-HD** [comment]
Having checked on master, this no longer happens 🙂
