### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by Stranger6667** [Zac-HD/hypothesis-jsonschema#77]
It turns out that `hypothesis-jsonschema` doesn't run on PyPy due to importing `_make_iterencode` from `json.encoder`. The fix should be quite straightforward, and I push a PR soon.

**Comment by Zac-HD** [comment]
Haha, I was so confident that it would work 😂

**Comment by Stranger6667** [comment]
You are welcome :)) Other than that and some implementation-dependent error messages, all tests are passing in Schemathesis with changes from #78 :)
